load test-plausibility .
*** load intruder .

mod TEST-INTRUDER-EMERGENCY is
  inc TEST-FOLLOWING-EMERGENCY .
***  inc INTRUDER-MODEL .
  inc INTRUDER-MODEL-SET .

 var n : Nat .
 var msgs : Msgs .
 var intr : Intruder .
 var conf : Conf .
 var attrs : AttributeSet .
 vars kb kb0 : KB .
 vars t0 t1 t2 : Nat .
 vars ff ff0 ff1 ffL ffH spdv0 spdv1 spdv2 : Rat .
 var int : Intruder .
 var asys : ASystem .
 var iasys : ASystemIntruder .
 var agent : Agent .
 var cl : Class .
 var id0 : Id .
 var env : Env .

 op imsgs : -> Msgs .

 op genMsgs : Rat Nat Msgs -> Msgs .
 eq genMsgs(ff,s n,msgs) 
  = genMsgs(ff,n,msg(v(0),v(1),"emergency",emergency)) . 
 eq genMsgs(ff,0,msgs) = msgs .

 op iid : -> Id .
 op intruder : Rat Nat -> Intruder .
 eq intruder(ff,n) 
   = [iid : intruder |
      (v2vMsgs : genMsgs(ff,n,none))
      (blockActSndSet : { v(0) ; false ; 0} )
***      (blockActSnd : v(0) ; 0)
      ] .

 op asysint : Rat Nat -> ASystemIntruder .
 eq asysint(ff, n) 
  = {emergency-scenario ; intruder(ff,n)} .


op fakeEmergency : ASystemIntruder -> Bool .
 op fakeEmergency$ : Env -> Bool .
 ceq fakeEmergency({ {conf env} ; int})
  = true 
  if fakeEmergency$(env) .

 
*** attack is successfull if v(1) stops (after fake emergency brake message) and v(0) and v(2) don't stop
  eq fakeEmergency$([id0 |
     (speed(v(0), spdv0) @ t0)  	
     (speed(v(1), spdv1) @ t1)  	
     (speed(v(2), spdv2) @ t2)
     kb]) = (spdv0 =/= 0)  and (spdv1 == 0) and (spdv2 =/= 0)  .

 op asys2 : -> ASystemIntruder .

 op crash : ASystemIntruder -> Bool .
 op crash$ : Env -> Bool .
 ceq crash({ {conf env} ; int})
  = true 
  if crash$(env) .

  eq crash$([id0 |
   (atloc(v(2), loc(ff1)) @ t1)
   (atloc(v(1), loc(ff0)) @ t0) 
    kb]) = ff1 >= ff0 .


endm

eof

*** new load; injection ***
search [1] in TEST-INTRUDER-EMERGENCY : asysint(70, 1) =>* iasys such that fakeEmergency(iasys) and crash(iasys) = true .

Solution 1 (state 2217)
states: 2218  rewrites: 670304 in 660ms cpu (666ms real) (1015612 rewrites/second)
iasys --> {{
[eId |
  clock(8) class(v(0), veh) class(v(1), veh) class(v(2), veh) class(i(0), infra) (atloc(v(0), loc(1200)) @ 8) (atloc(v(1), loc(1022)) @ 8) (atloc(v(2), loc(1029)) @ 8) (speed(v(0), 25) @ 8) (speed(v(1),
    0) @ 8) (speed(v(2), 6) @ 8) (accel(v(0), 0) @ 8) (accel(v(1), 0) @ 8) accel(v(2), 0) @ 8] 
[v(0) : veh |
  lkb : (clock(8) class(v(0), veh) (lastAct(actSpeed(v(0), 22, 28)) @ 7) (atloc(v(0), loc(1175)) @ 7) (atloc(v(1), loc(945)) @ 0) (atloc(v(2), loc(1009)) @ 6) (mode(v(0), leading(none)) @ 0) (platoon(v(
    0), v(1) ; v(2)) @ 0) (speed(v(0), 25) @ 7) (speed(v(1), 20) @ 0) (speed(v(2), 11) @ 6) maxAcc(v(0), 3)),
  ckb : none,
  sensors : (locS speedS gapS),
  evs : ((tick @ 0) v2v(v(0), msg(v(2), v(0), hbf2l(v(2), 9, loc(1020))) @ 7) @ 0)] 
[v(1) : veh |
  lkb : (clock(8) class(v(1), veh) (lastAct(actSpeed(v(1), 0, 0)) @ 7) (atloc(v(1), loc(1022)) @ 7) (mode(v(1), emergency) @ 0) (histGap(v(1), noVal ; noVal ; noVal) @ 0) (speed(v(1), 0) @ 7) (gapNext(v(
    1), 153) @ 7) (idNext(v(1), v(0)) @ 0) (logSpdPlCkFail(v(1), v(0), 0) @ 0) (histSpd(v(1), v(0), noVal ; noVal ; noVal) @ 0) (histSpd(v(1), v(2), noVal ; noVal ; noVal) @ 0) maxAcc(v(1), 3) gapGreen(
    v(1), 1, 3) gapSafety(v(1), 2, 4)),
  ckb : none,
  sensors : (locS speedS gapS),
  evs : ((tick @ 0) v2v(v(1), msg(v(0), v(1), hbl2f(v(0), 25, loc(1175), (atloc(v(1), loc(945)) @ 0) (atloc(v(2), loc(1009)) @ 6) (platoon(v(0), v(1) ; v(2)) @ 0) (speed(v(1), 20) @ 0) speed(v(2), 11) @
    6)) @ 7) @ 0)] 
[v(2) : veh |
  lkb : (clock(8) class(v(2), veh) (lastAct(actSpeed(v(2), 6, 22/3)) @ 7) (atloc(v(0), loc(1150)) @ 6) (atloc(v(1), loc(945)) @ 0) (atloc(v(2), loc(1020)) @ 7) (mode(v(2), following(v(0))) @ 0) (platoon(
    v(0), v(1) ; v(2)) @ 0) (histGap(v(2), (2 @ 7) ; (11 @ 6) ; 18 @ 5) @ 7) (speed(v(0), 25) @ 6) (speed(v(1), 20) @ 0) (speed(v(2), 9) @ 7) (gapNext(v(2), 2) @ 7) (idNext(v(2), v(1)) @ 0) (
    logSpdPlCkFail(v(2), v(1), 0) @ 0) (histSpd(v(2), v(0), (25 @ 6) ; (25 @ 5) ; 25 @ 4) @ 6) (histSpd(v(2), v(1), (20 @ 0) ; noVal ; noVal) @ 0) maxAcc(v(2), 3) gapGreen(v(2), 1, 3) gapSafety(v(2), 2,
    4)),
  ckb : none,
  sensors : (locS speedS gapS),
  evs : ((tick @ 0) v2v(v(2), msg(v(0), v(2), hbl2f(v(0), 25, loc(1175), (atloc(v(1), loc(945)) @ 0) (atloc(v(2), loc(1009)) @ 6) (platoon(v(0), v(1) ; v(2)) @ 0) (speed(v(1), 20) @ 0) speed(v(2), 11) @
    6)) @ 7) @ 0)] 
[i(0) : infra |
  lkb : (clock(8) (atloc(v(0), loc(1175)) @ 7) (atloc(v(1), loc(1022)) @ 7) (atloc(v(2), loc(1020)) @ 7) (i2vTrigger(i(0), v(2), 500, 50, nuPlatoon) @ 0) i2vTrigger(i(0), v(2), 600, 50, join(v(0))) @ 0),
  ckb : none,
  sensors : vehS,
  evs : (tick @ 0)]} ; 
[iid : intruder |
  v2vMsgs : none
  blockActSndSet : {v(0) ; false ; 0}]}



*** new load; injection + blocking ***
search [1] in TEST-INTRUDER-EMERGENCY : asysint(70, 1) =>* iasys such that fakeEmergency(iasys) and crash(iasys) = true .

Solution 1 (state 592)
states: 593  rewrites: 110394 in 124ms cpu (123ms real) (890274 rewrites/second)
iasys --> {{
[eId |
  clock(9) class(v(0), veh) class(v(1), veh) class(v(2), veh) class(i(0), infra) (atloc(v(0), loc(1225)) @ 9) (atloc(v(1), loc(1022)) @ 9) (atloc(v(2), loc(1023)) @ 9) (speed(v(0), 25) @ 9) (speed(v(1),
    0) @ 9) (speed(v(2), 2) @ 9) (accel(v(0), 0) @ 9) (accel(v(1), 0) @ 9) accel(v(2), 0) @ 9] 
[v(0) : veh |
  lkb : (clock(9) class(v(0), veh) (lastAct(actSpeed(v(0), 22, 28)) @ 8) (atloc(v(0), loc(1200)) @ 8) (atloc(v(1), loc(945)) @ 0) (atloc(v(2), loc(1011)) @ 7) (mode(v(0), leading(none)) @ 0) (platoon(v(
    0), v(1) ; v(2)) @ 0) (speed(v(0), 25) @ 8) (speed(v(1), 20) @ 0) (speed(v(2), 7) @ 7) maxAcc(v(0), 3)),
  ckb : none,
  sensors : (locS speedS gapS),
  evs : ((tick @ 0) v2v(v(0), msg(v(2), v(0), hbf2l(v(2), 5, loc(1018))) @ 8) @ 0)] 
[v(1) : veh |
  lkb : (clock(9) class(v(1), veh) (lastAct(actSpeed(v(1), 0, 0)) @ 8) (atloc(v(1), loc(1022)) @ 8) (mode(v(1), emergency) @ 0) (histGap(v(1), noVal ; noVal ; noVal) @ 0) (speed(v(1), 0) @ 8) (gapNext(v(
    1), 178) @ 8) (idNext(v(1), v(0)) @ 0) (logSpdPlCkFail(v(1), v(0), 0) @ 0) (histSpd(v(1), v(0), noVal ; noVal ; noVal) @ 0) (histSpd(v(1), v(2), noVal ; noVal ; noVal) @ 0) maxAcc(v(1), 3) gapGreen(
    v(1), 1, 3) gapSafety(v(1), 2, 4)),
  ckb : none,
  sensors : (locS speedS gapS),
  evs : (tick @ 0)] 
[v(2) : veh |
  lkb : (clock(9) class(v(2), veh) (lastAct(actSpeed(v(2), 9/4, 3)) @ 8) (atloc(v(2), loc(1018)) @ 8) (mode(v(2), following(v(0))) @ 0) (histGap(v(2), noVal ; noVal ; noVal) @ 0) (speed(v(2), 5) @ 8) (
    gapNext(v(2), 4) @ 8) (idNext(v(2), v(1)) @ 0) (logSpdPlCkFail(v(2), v(1), 0) @ 0) (histSpd(v(2), v(0), noVal ; noVal ; noVal) @ 0) (histSpd(v(2), v(1), noVal ; noVal ; noVal) @ 0) maxAcc(v(2), 3)
    gapGreen(v(2), 1, 3) gapSafety(v(2), 2, 4)),
  ckb : none,
  sensors : (locS speedS gapS),
  evs : (tick @ 0)] 
[i(0) : infra |
  lkb : (clock(9) (atloc(v(0), loc(1200)) @ 8) (atloc(v(1), loc(1022)) @ 8) (atloc(v(2), loc(1018)) @ 8) (i2vTrigger(i(0), v(2), 500, 50, nuPlatoon) @ 0) i2vTrigger(i(0), v(2), 600, 50, join(v(0))) @ 0),
  ckb : none,
  sensors : vehS,
  evs : (tick @ 0)]} ; 
[iid : intruder |
  v2vMsgs : none
  blockActSndSet : {v(0) ; true ; 0}]}






*** without blocking messages from v(0) ***
search [1] in TEST-INTRUDER-EMERGENCY : asysint(70, 1) =>* iasys such that fakeEmergency(iasys) and crash(iasys) .
Solution 1 (state 1273)
states: 1274  rewrites: 3277880 in 3040ms cpu (3039ms real) (1078250 rewrites/second)
iasys --> {{
[eId |
  clock(8) class(v(0), veh) class(v(1), veh) class(v(2), veh) class(i(0), infra) (atloc(v(0), loc(1200)) @ 8) (atloc(v(1), loc(1022)) @ 8) (atloc(v(2), loc(1029)) @ 8) (speed(v(0), 25) @ 8) (speed(v(1),
    0) @ 8) (speed(v(2), 6) @ 8) (accel(v(0), 0) @ 8) (accel(v(1), 0) @ 8) accel(v(2), 0) @ 8] 
[v(0) : veh |
  lkb : (clock(8) class(v(0), veh) (lastAct(actSpeed(v(0), 22, 28)) @ 7) (atloc(v(0), loc(1175)) @ 7) (atloc(v(1), loc(945)) @ 0) (atloc(v(2), loc(1009)) @ 6) (mode(v(0), leading(none)) @ 0) (platoon(v(
    0), v(1) ; v(2)) @ 0) (speed(v(0), 25) @ 7) (speed(v(1), 20) @ 0) (speed(v(2), 11) @ 6) maxAcc(v(0), 3)),
  ckb : none,
  sensors : (locS speedS gapS),
  evs : ((tick @ 0) v2v(v(0), msg(v(2), v(0), hbf2l(v(2), 9, loc(1020))) @ 7) @ 0)] 
[v(1) : veh |
  lkb : (clock(8) class(v(1), veh) (lastAct(actSpeed(v(1), 0, 0)) @ 7) (atloc(v(1), loc(1022)) @ 7) (mode(v(1), emergency) @ 0) (histGap(v(1), noVal ; noVal ; noVal) @ 0) (speed(v(1), 0) @ 7) (gapNext(v(
    1), 153) @ 7) (idNext(v(1), v(0)) @ 0) (logSpdPlCkFail(v(1), v(0), 0) @ 0) (histSpd(v(1), v(0), noVal ; noVal ; noVal) @ 0) (histSpd(v(1), v(2), noVal ; noVal ; noVal) @ 0) maxAcc(v(1), 3) gapGreen(
    v(1), 1, 3) gapSafety(v(1), 2, 4)),
  ckb : none,
  sensors : (locS speedS gapS),
  evs : ((tick @ 0) v2v(v(1), msg(v(0), v(1), hbl2f(v(0), 25, loc(1175), (atloc(v(1), loc(945)) @ 0) (atloc(v(2), loc(1009)) @ 6) (platoon(v(0), v(1) ; v(2)) @ 0) (speed(v(1), 20) @ 0) speed(v(2), 11) @
    6)) @ 7) @ 0)] 
[v(2) : veh |
  lkb : (clock(8) class(v(2), veh) (lastAct(actSpeed(v(2), 6, 22/3)) @ 7) (atloc(v(0), loc(1150)) @ 6) (atloc(v(1), loc(945)) @ 0) (atloc(v(2), loc(1020)) @ 7) (mode(v(2), following(v(0))) @ 0) (platoon(
    v(0), v(1) ; v(2)) @ 0) (histGap(v(2), (2 @ 7) ; (11 @ 6) ; 18 @ 5) @ 7) (speed(v(0), 25) @ 6) (speed(v(1), 20) @ 0) (speed(v(2), 9) @ 7) (gapNext(v(2), 2) @ 7) (idNext(v(2), v(1)) @ 0) (
    logSpdPlCkFail(v(2), v(1), 0) @ 0) (histSpd(v(2), v(0), (25 @ 6) ; (25 @ 5) ; 25 @ 4) @ 6) (histSpd(v(2), v(1), (20 @ 0) ; noVal ; noVal) @ 0) maxAcc(v(2), 3) gapGreen(v(2), 1, 3) gapSafety(v(2), 2,
    4)),
  ckb : none,
  sensors : (locS speedS gapS),
  evs : ((tick @ 0) v2v(v(2), msg(v(0), v(2), hbl2f(v(0), 25, loc(1175), (atloc(v(1), loc(945)) @ 0) (atloc(v(2), loc(1009)) @ 6) (platoon(v(0), v(1) ; v(2)) @ 0) (speed(v(1), 20) @ 0) speed(v(2), 11) @
    6)) @ 7) @ 0)] 
[i(0) : infra |
  lkb : (clock(8) (atloc(v(0), loc(1175)) @ 7) (atloc(v(1), loc(1022)) @ 7) (atloc(v(2), loc(1020)) @ 7) (i2vTrigger(i(0), v(2), 500, 50, nuPlatoon) @ 0) i2vTrigger(i(0), v(2), 600, 50, join(v(0))) @ 0),
  ckb : none,
  sensors : vehS,
  evs : (tick @ 0)]} ; 
[iid : intruder |
  v2vMsgs : none
  blockActSnd : v(5) ; 0]}


*** with # blocked messaged enabled ***
search [1] in TEST-INTRUDER-EMERGENCY : asysint(70, 1) =>* iasys such that fakeEmergency(iasys) and crash(iasys) .

Solution 1 (state 47033)
states: 47034  rewrites: 78133518 in 93796ms cpu (93800ms real) (833015 rewrites/second)
iasys --> {{
[eId |
  clock(8) class(v(0), veh) class(v(1), veh) class(v(2), veh) class(i(0), infra) (atloc(v(0), loc(1200)) @ 8) (atloc(v(1), loc(1022)) @ 8) (atloc(v(2), loc(1029)) @ 8) (speed(v(0), 25) @ 8) (speed(v(1),
    0) @ 8) (speed(v(2), 6) @ 8) (accel(v(0), 0) @ 8) (accel(v(1), 0) @ 8) accel(v(2), 0) @ 8] 
[v(0) : veh |
  lkb : (clock(8) class(v(0), veh) (lastAct(actSpeed(v(0), 22, 28)) @ 7) (atloc(v(0), loc(1175)) @ 7) (atloc(v(1), loc(945)) @ 0) (atloc(v(2), loc(1009)) @ 6) (mode(v(0), leading(none)) @ 0) (platoon(v(
    0), v(1) ; v(2)) @ 0) (speed(v(0), 25) @ 7) (speed(v(1), 20) @ 0) (speed(v(2), 11) @ 6) maxAcc(v(0), 3)),
  ckb : none,
  sensors : (locS speedS gapS),
  evs : ((tick @ 0) v2v(v(0), msg(v(2), v(0), hbf2l(v(2), 9, loc(1020))) @ 7) @ 0)] 
[v(1) : veh |
  lkb : (clock(8) class(v(1), veh) (lastAct(actSpeed(v(1), 0, 0)) @ 7) (atloc(v(1), loc(1022)) @ 7) (mode(v(1), emergency) @ 0) (histGap(v(1), noVal ; noVal ; noVal) @ 0) (speed(v(1), 0) @ 7) (gapNext(v(
    1), 153) @ 7) (idNext(v(1), v(0)) @ 0) (logSpdPlCkFail(v(1), v(0), 0) @ 0) (histSpd(v(1), v(0), noVal ; noVal ; noVal) @ 0) (histSpd(v(1), v(2), noVal ; noVal ; noVal) @ 0) maxAcc(v(1), 3) gapGreen(
    v(1), 1, 3) gapSafety(v(1), 2, 4)),
  ckb : none,
  sensors : (locS speedS gapS),
  evs : ((tick @ 0) v2v(v(1), msg(v(0), v(1), hbl2f(v(0), 25, loc(1175), (atloc(v(1), loc(945)) @ 0) (atloc(v(2), loc(1009)) @ 6) (platoon(v(0), v(1) ; v(2)) @ 0) (speed(v(1), 20) @ 0) speed(v(2), 11) @
    6)) @ 7) @ 0)] 
[v(2) : veh |
  lkb : (clock(8) class(v(2), veh) (lastAct(actSpeed(v(2), 6, 22/3)) @ 7) (atloc(v(0), loc(1150)) @ 6) (atloc(v(1), loc(945)) @ 0) (atloc(v(2), loc(1020)) @ 7) (mode(v(2), following(v(0))) @ 0) (platoon(
    v(0), v(1) ; v(2)) @ 0) (histGap(v(2), (2 @ 7) ; (11 @ 6) ; 18 @ 5) @ 7) (speed(v(0), 25) @ 6) (speed(v(1), 20) @ 0) (speed(v(2), 9) @ 7) (gapNext(v(2), 2) @ 7) (idNext(v(2), v(1)) @ 0) (
    logSpdPlCkFail(v(2), v(1), 0) @ 0) (histSpd(v(2), v(0), (25 @ 6) ; (25 @ 5) ; 25 @ 4) @ 6) (histSpd(v(2), v(1), (20 @ 0) ; noVal ; noVal) @ 0) maxAcc(v(2), 3) gapGreen(v(2), 1, 3) gapSafety(v(2), 2,
    4)),
  ckb : none,
  sensors : (locS speedS gapS),
  evs : ((tick @ 0) v2v(v(2), msg(v(0), v(2), hbl2f(v(0), 25, loc(1175), (atloc(v(1), loc(945)) @ 0) (atloc(v(2), loc(1009)) @ 6) (platoon(v(0), v(1) ; v(2)) @ 0) (speed(v(1), 20) @ 0) speed(v(2), 11) @
    6)) @ 7) @ 0)] 
[i(0) : infra |
  lkb : (clock(8) (atloc(v(0), loc(1175)) @ 7) (atloc(v(1), loc(1022)) @ 7) (atloc(v(2), loc(1020)) @ 7) (i2vTrigger(i(0), v(2), 500, 50, nuPlatoon) @ 0) i2vTrigger(i(0), v(2), 600, 50, join(v(0))) @ 0),
  ckb : none,
  sensors : vehS,
  evs : (tick @ 0)]} ; 
[iid : intruder |
  v2vMsgs : none
  blockActSnd : v(0) ; 0]}

search [1] in TEST-INTRUDER-EMERGENCY : asysint(70, 1) =>* iasys such that fakeEmergency(iasys) = true .

Solution 1 (state 4525)
states: 4526  rewrites: 7186052 in 6900ms cpu (6899ms real) (1041456 rewrites/second)
iasys --> {{
[eId |
  clock(5) class(v(0), veh) class(v(1), veh) class(v(2), veh) class(i(0), infra) (atloc(v(0), loc(1100)) @ 5) (atloc(v(1), loc(1045)) @ 5) (atloc(v(2), loc(155)) @ 5) (speed(v(0), 20) @ 5) (speed(v(1), 20) @ 5) (speed(v(2), 0) @ 5) (accel(v(0), 0) @ 5) (accel(v(1), 0) @ 5) accel(
    v(2), 0) @ 5] 
[v(0) : veh |
  lkb : (clock(5) class(v(0), veh) (lastAct(actSpeed(v(0), 17, 23)) @ 4) (atloc(v(0), loc(1080)) @ 4) (atloc(v(1), loc(1005)) @ 3) (atloc(v(2), loc(895)) @ 0) (mode(v(0), leading(none)) @ 0) (platoon(v(0), v(1) ; v(2)) @ 0) (speed(v(0), 20) @ 4) (speed(v(1), 20) @ 3) (speed(v(2),
    15) @ 0) maxAcc(v(0), 3)),
  ckb : none,
  sensors : (locS speedS gapS),
  evs : ((tick @ 0) v2v(v(0), msg(v(1), v(0), hbf2l(v(1), 20, loc(1025))) @ 4) @ 0)] 
[v(1) : veh |
  lkb : (clock(5) class(v(1), veh) (lastAct(actSpeed(v(1), 75/4, 23)) @ 4) (atloc(v(0), loc(1060)) @ 3) (atloc(v(1), loc(1025)) @ 4) (atloc(v(2), loc(895)) @ 0) (mode(v(1), following(v(0))) @ 0) (platoon(v(0), v(1) ; v(2)) @ 0) (histGap(v(1), (55 @ 4) ; (55 @ 3) ; 55 @ 2) @ 4) (
    speed(v(0), 20) @ 3) (speed(v(1), 20) @ 4) (speed(v(2), 15) @ 0) (gapNext(v(1), 55) @ 4) (idNext(v(1), v(0)) @ 0) (histSpd(v(1), v(0), (20 @ 3) ; (20 @ 2) ; 20 @ 1) @ 3) (histSpd(v(1), v(2), (15 @ 0) ; noVal ; noVal) @ 0) maxAcc(v(1), 3) gapGreen(v(1), 1, 3) gapSafety(v(1), 2,
    4)),
  ckb : none,
  sensors : (locS speedS gapS),
  evs : ((tick @ 0) v2v(v(1), msg(v(0), v(1), hbl2f(v(0), 20, loc(1080), (atloc(v(1), loc(1005)) @ 3) (atloc(v(2), loc(895)) @ 0) (platoon(v(0), v(1) ; v(2)) @ 0) (speed(v(1), 20) @ 3) speed(v(2), 15) @ 0)) @ 4) @ 0)] 
[v(2) : veh |
  lkb : (clock(5) class(v(2), veh) (lastAct(actSpeed(v(2), 0, 0)) @ 4) (atloc(v(2), loc(152)) @ 4) (mode(v(2), emergency) @ 0) (histGap(v(2), noVal ; noVal ; noVal) @ 0) (speed(v(1), 20) @ 0) (speed(v(2), 3) @ 4) (gapNext(v(2), 873) @ 4) (idNext(v(2), v(1)) @ 0) (histSpd(v(2), v(
    0), noVal ; noVal ; noVal) @ 0) (histSpd(v(2), v(1), noVal ; noVal ; noVal) @ 0) maxAcc(v(2), 3) gapGreen(v(2), 1, 3) gapSafety(v(2), 2, 4)),
  ckb : none,
  sensors : (locS speedS gapS),
  evs : ((tick @ 0) v2v(v(2), msg(v(0), v(2), hbl2f(v(0), 20, loc(1080), (atloc(v(1), loc(1005)) @ 3) (atloc(v(2), loc(895)) @ 0) (platoon(v(0), v(1) ; v(2)) @ 0) (speed(v(1), 20) @ 3) speed(v(2), 15) @ 0)) @ 4) @ 0)] 
[i(0) : infra |
  lkb : (clock(5) (atloc(v(0), loc(1080)) @ 4) (atloc(v(1), loc(1025)) @ 4) (atloc(v(2), loc(152)) @ 4) (i2vTrigger(i(0), v(2), 500, 50, nuPlatoon) @ 0) i2vTrigger(i(0), v(2), 600, 50, join(v(0))) @ 0),
  ckb : none,
  sensors : vehS,
  evs : (tick @ 0)]} ; 
[iid : intruder |
  v2vMsgs : none
  blockActSnd : v(0)]}


*** eq tminSaf = 2 . 
*** eq tmaxSaf = 4 .
search [1] in TEST-INTRUDER-EMERGENCY : asysint(70, 1) =>* iasys such that crash(iasys) = true .

Solution 1 (state 42770)
states: 42771  rewrites: 65712626 in 75952ms cpu (75951ms real) (865186 rewrites/second)
iasys --> {{
[eId |
  clock(8) class(v(0), veh) class(v(1), veh) class(v(2), veh) class(i(0), infra) (atloc(v(0), loc(1200)) @ 8) (atloc(v(1), loc(1022)) @ 8) (atloc(v(2), loc(1029)) @ 8) (speed(v(0), 25) @ 8) (speed(v(1),
    0) @ 8) (speed(v(2), 6) @ 8) (accel(v(0), 0) @ 8) (accel(v(1), 0) @ 8) accel(v(2), 0) @ 8] 
[v(0) : veh |
  lkb : (clock(8) class(v(0), veh) (lastAct(actSpeed(v(0), 22, 28)) @ 7) (atloc(v(0), loc(1175)) @ 7) (atloc(v(1), loc(945)) @ 0) (atloc(v(2), loc(1009)) @ 6) (mode(v(0), leading(none)) @ 0) (platoon(v(
    0), v(1) ; v(2)) @ 0) (speed(v(0), 25) @ 7) (speed(v(1), 20) @ 0) (speed(v(2), 11) @ 6) maxAcc(v(0), 3)),
  ckb : none,
  sensors : (locS speedS gapS),
  evs : ((tick @ 0) v2v(v(0), msg(v(2), v(0), hbf2l(v(2), 9, loc(1020))) @ 7) @ 0)] 
[v(1) : veh |
  lkb : (clock(8) class(v(1), veh) (lastAct(actSpeed(v(1), 0, 0)) @ 7) (atloc(v(1), loc(1022)) @ 7) (mode(v(1), emergency) @ 0) (histGap(v(1), noVal ; noVal ; noVal) @ 0) (speed(v(1), 0) @ 7) (gapNext(v(
    1), 153) @ 7) (idNext(v(1), v(0)) @ 0) (histSpd(v(1), v(0), noVal ; noVal ; noVal) @ 0) (histSpd(v(1), v(2), noVal ; noVal ; noVal) @ 0) maxAcc(v(1), 3) gapGreen(v(1), 1, 3) gapSafety(v(1), 2, 4)),
  ckb : none,
  sensors : (locS speedS gapS),
  evs : ((tick @ 0) v2v(v(1), msg(v(0), v(1), hbl2f(v(0), 25, loc(1175), (atloc(v(1), loc(945)) @ 0) (atloc(v(2), loc(1009)) @ 6) (platoon(v(0), v(1) ; v(2)) @ 0) (speed(v(1), 20) @ 0) speed(v(2), 11) @
    6)) @ 7) @ 0)] 
[v(2) : veh |
  lkb : (clock(8) class(v(2), veh) (lastAct(actSpeed(v(2), 6, 22/3)) @ 7) (atloc(v(0), loc(1150)) @ 6) (atloc(v(1), loc(945)) @ 0) (atloc(v(2), loc(1020)) @ 7) (mode(v(2), following(v(0))) @ 0) (platoon(
    v(0), v(1) ; v(2)) @ 0) (histGap(v(2), (2 @ 7) ; (11 @ 6) ; 18 @ 5) @ 7) (speed(v(0), 25) @ 6) (speed(v(1), 20) @ 0) (speed(v(2), 9) @ 7) (gapNext(v(2), 2) @ 7) (idNext(v(2), v(1)) @ 0) (histSpd(v(
    2), v(0), (25 @ 6) ; (25 @ 5) ; 25 @ 4) @ 6) (histSpd(v(2), v(1), (20 @ 0) ; noVal ; noVal) @ 0) maxAcc(v(2), 3) gapGreen(v(2), 1, 3) gapSafety(v(2), 2, 4)),
  ckb : none,
  sensors : (locS speedS gapS),
  evs : ((tick @ 0) v2v(v(2), msg(v(0), v(2), hbl2f(v(0), 25, loc(1175), (atloc(v(1), loc(945)) @ 0) (atloc(v(2), loc(1009)) @ 6) (platoon(v(0), v(1) ; v(2)) @ 0) (speed(v(1), 20) @ 0) speed(v(2), 11) @
    6)) @ 7) @ 0)] 
[i(0) : infra |
  lkb : (clock(8) (atloc(v(0), loc(1175)) @ 7) (atloc(v(1), loc(1022)) @ 7) (atloc(v(2), loc(1020)) @ 7) (i2vTrigger(i(0), v(2), 500, 50, nuPlatoon) @ 0) i2vTrigger(i(0), v(2), 600, 50, join(v(0))) @ 0),
  ckb : none,
  sensors : vehS,
  evs : (tick @ 0)]} ; 
[iid : intruder |
  v2vMsgs : none
  blockActSnd : v(0)]}

*** eq tminSaf = 4 . 
*** eq tmaxSaf = 6 .
search [1] in TEST-INTRUDER-EMERGENCY : asysint(70, 1) =>* iasys such that crash(iasys) = true .

Solution 1 (state 158945)
states: 158946  rewrites: 243815809 in 369108ms cpu (369117ms real) (660554 rewrites/second)
iasys --> {{
[eId |
  clock(10) class(v(0), veh) class(v(1), veh) class(v(2), veh) class(i(0), infra) (atloc(v(0), loc(1250)) @ 10) (atloc(v(1), loc(1022)) @ 10) (atloc(v(2), loc(1024)) @ 10) (speed(v(0), 25) @ 10) (speed(v(1), 0) @ 10) (speed(v(2), 3) @ 10) (accel(v(0), 0) @ 10) (accel(v(1), 0) @
    10) accel(v(2), 0) @ 10] 
[v(0) : veh |
  lkb : (clock(10) class(v(0), veh) (lastAct(actSpeed(v(0), 22, 28)) @ 9) (atloc(v(0), loc(1225)) @ 9) (atloc(v(1), loc(945)) @ 0) (atloc(v(2), loc(1014)) @ 8) (mode(v(0), leading(none)) @ 0) (platoon(v(0), v(1) ; v(2)) @ 0) (speed(v(0), 25) @ 9) (speed(v(1), 20) @ 0) (speed(v(2),
    6) @ 8) maxAcc(v(0), 3)),
  ckb : none,
  sensors : (locS speedS gapS),
  evs : ((tick @ 0) v2v(v(0), msg(v(2), v(0), hbf2l(v(2), 4, loc(1020))) @ 9) @ 0)] 
[v(1) : veh |
  lkb : (clock(10) class(v(1), veh) (lastAct(actSpeed(v(1), 0, 0)) @ 9) (atloc(v(1), loc(1022)) @ 9) (mode(v(1), emergency) @ 0) (histGap(v(1), noVal ; noVal ; noVal) @ 0) (speed(v(1), 0) @ 9) (gapNext(v(1), 203) @ 9) (idNext(v(1), v(0)) @ 0) (histSpd(v(1), v(0), noVal ; noVal ;
    noVal) @ 0) (histSpd(v(1), v(2), noVal ; noVal ; noVal) @ 0) maxAcc(v(1), 3) gapGreen(v(1), 1, 3) gapSafety(v(1), 4, 6)),
  ckb : none,
  sensors : (locS speedS gapS),
  evs : ((tick @ 0) v2v(v(1), msg(v(0), v(1), hbl2f(v(0), 25, loc(1225), (atloc(v(1), loc(945)) @ 0) (atloc(v(2), loc(1014)) @ 8) (platoon(v(0), v(1) ; v(2)) @ 0) (speed(v(1), 20) @ 0) speed(v(2), 6) @ 8)) @ 9) @ 0)] 
[v(2) : veh |
  lkb : (clock(10) class(v(2), veh) (lastAct(actSpeed(v(2), 22/7, 22/5)) @ 9) (atloc(v(0), loc(1200)) @ 8) (atloc(v(1), loc(945)) @ 0) (atloc(v(2), loc(1020)) @ 9) (mode(v(2), following(v(0))) @ 0) (platoon(v(0), v(1) ; v(2)) @ 0) (histGap(v(2), (2 @ 9) ; (8 @ 8) ; 16 @ 7) @ 9) (
    speed(v(0), 25) @ 8) (speed(v(1), 20) @ 0) (speed(v(2), 4) @ 9) (gapNext(v(2), 2) @ 9) (idNext(v(2), v(1)) @ 0) (histSpd(v(2), v(0), (25 @ 8) ; (25 @ 7) ; 25 @ 6) @ 8) (histSpd(v(2), v(1), (20 @ 0) ; noVal ; noVal) @ 0) maxAcc(v(2), 3) gapGreen(v(2), 1, 3) gapSafety(v(2), 4,
    6)),
  ckb : none,
  sensors : (locS speedS gapS),
  evs : ((tick @ 0) v2v(v(2), msg(v(0), v(2), hbl2f(v(0), 25, loc(1225), (atloc(v(1), loc(945)) @ 0) (atloc(v(2), loc(1014)) @ 8) (platoon(v(0), v(1) ; v(2)) @ 0) (speed(v(1), 20) @ 0) speed(v(2), 6) @ 8)) @ 9) @ 0)] 
[i(0) : infra |
  lkb : (clock(10) (atloc(v(0), loc(1225)) @ 9) (atloc(v(1), loc(1022)) @ 9) (atloc(v(2), loc(1020)) @ 9) (i2vTrigger(i(0), v(2), 500, 50, nuPlatoon) @ 0) i2vTrigger(i(0), v(2), 600, 50, join(v(0))) @ 0),
  ckb : none,
  sensors : vehS,
  evs : (tick @ 0)]} ; 
[iid : intruder |
  v2vMsgs : none
  blockActSnd : v(0)]}



*** eq tminSaf = 6 . 
*** eq tmaxSaf = 8 .
search [1] in TEST-INTRUDER-EMERGENCY : asysint(70, 1) =>* iasys such that crash(iasys) = true .

Solution 1 (state 96119)
states: 96120  rewrites: 150168487 in 158008ms cpu (158007ms real) (950385 rewrites/second)
iasys --> {{
[eId |
  clock(12) class(v(0), veh) class(v(1), veh) class(v(2), veh) class(i(0), infra) (atloc(v(0), loc(1300)) @ 12) (atloc(v(1), loc(1022)) @ 12) (atloc(v(2), loc(1024)) @ 12) (speed(v(0), 25) @ 12) (speed(v(1), 0) @ 12) (speed(v(2), 2) @ 12) (accel(v(0), 0) @ 12) (accel(v(1), 0) @
    12) accel(v(2), 0) @ 12] 
[v(0) : veh |
  lkb : (clock(12) class(v(0), veh) (lastAct(actSpeed(v(0), 22, 28)) @ 11) (atloc(v(0), loc(1275)) @ 11) (atloc(v(1), loc(945)) @ 0) (atloc(v(2), loc(1017)) @ 10) (mode(v(0), leading(none)) @ 0) (platoon(v(0), v(1) ; v(2)) @ 0) (speed(v(0), 25) @ 11) (speed(v(1), 20) @ 0) (speed(
    v(2), 4) @ 10) maxAcc(v(0), 3)),
  ckb : none,
  sensors : (locS speedS gapS),
  evs : ((tick @ 0) v2v(v(0), msg(v(2), v(0), hbf2l(v(2), 3, loc(1021))) @ 11) @ 0)] 
[v(1) : veh |
  lkb : (clock(12) class(v(1), veh) (lastAct(actSpeed(v(1), 0, 0)) @ 11) (atloc(v(1), loc(1022)) @ 11) (mode(v(1), emergency) @ 0) (histGap(v(1), noVal ; noVal ; noVal) @ 0) (speed(v(1), 0) @ 11) (gapNext(v(1), 253) @ 11) (idNext(v(1), v(0)) @ 0) (histSpd(v(1), v(0), noVal ; noVal
    ; noVal) @ 0) (histSpd(v(1), v(2), noVal ; noVal ; noVal) @ 0) maxAcc(v(1), 3) gapGreen(v(1), 1, 3) gapSafety(v(1), 6, 8)),
  ckb : none,
  sensors : (locS speedS gapS),
  evs : ((tick @ 0) v2v(v(1), msg(v(0), v(1), hbl2f(v(0), 25, loc(1275), (atloc(v(1), loc(945)) @ 0) (atloc(v(2), loc(1017)) @ 10) (platoon(v(0), v(1) ; v(2)) @ 0) (speed(v(1), 20) @ 0) speed(v(2), 4) @ 10)) @ 11) @ 0)] 
[v(2) : veh |
  lkb : (clock(12) class(v(2), veh) (lastAct(actSpeed(v(2), 7/3, 3)) @ 11) (atloc(v(0), loc(1250)) @ 10) (atloc(v(1), loc(945)) @ 0) (atloc(v(2), loc(1021)) @ 11) (mode(v(2), following(v(0))) @ 0) (platoon(v(0), v(1) ; v(2)) @ 0) (histGap(v(2), (1 @ 11) ; (5 @ 10) ; 9 @ 9) @ 11) (
    speed(v(0), 25) @ 10) (speed(v(1), 20) @ 0) (speed(v(2), 3) @ 11) (gapNext(v(2), 1) @ 11) (idNext(v(2), v(1)) @ 0) (histSpd(v(2), v(0), (25 @ 10) ; (25 @ 9) ; 25 @ 8) @ 10) (histSpd(v(2), v(1), (20 @ 0) ; noVal ; noVal) @ 0) maxAcc(v(2), 3) gapGreen(v(2), 1, 3) gapSafety(v(2),
    6, 8)),
  ckb : none,
  sensors : (locS speedS gapS),
  evs : ((tick @ 0) v2v(v(2), msg(v(0), v(2), hbl2f(v(0), 25, loc(1275), (atloc(v(1), loc(945)) @ 0) (atloc(v(2), loc(1017)) @ 10) (platoon(v(0), v(1) ; v(2)) @ 0) (speed(v(1), 20) @ 0) speed(v(2), 4) @ 10)) @ 11) @ 0)] 
[i(0) : infra |
  lkb : (clock(12) (atloc(v(0), loc(1275)) @ 11) (atloc(v(1), loc(1022)) @ 11) (atloc(v(2), loc(1021)) @ 11) (i2vTrigger(i(0), v(2), 500, 50, nuPlatoon) @ 0) i2vTrigger(i(0), v(2), 600, 50, join(v(0))) @ 0),
  ckb : none,
  sensors : vehS,
  evs : (tick @ 0)]} ; 
[iid : intruder |
  v2vMsgs : none
  blockActSnd : v(0)]}
