load test-plausibility .
 *** load intruder .

mod TEST-INTRUDER is
  inc TEST-SIMPLE-FOLLOWING .
 *** inc INTRUDER-MODEL .
  inc INTRUDER-MODEL-SET .  

 var n : Nat .
 var msgs : Msgs .
 var intr : Intruder .
 var conf : Conf .
 var attrs : AttributeSet .
 vars kb kb0 : KB .
 vars t0 t1 t2 cnt : Nat .
 vars ff ff0 ff1 ffL ffH : Rat .
 var int : Intruder .
 vars asys scario : ASystem .
 var iasys : ASystemIntruder .
 vars agent agent1 agent2 agent3 : Agent . 
 var cl : Class .
 var id0 : Id .
 var env : Env .
 var evs : EventSet . 

 op imsgs : -> Msgs .

 op genMsgs : Rat Nat Msgs -> Msgs .
 eq genMsgs(ff,s n,msgs) 
  = genMsgs(ff,n,msg(v(0),v(1), 
    hbl2f(v(0),ff,loc(2000 + ff * (s n)),none)) msgs) .
 eq genMsgs(ff,0,msgs) = msgs .

 op iid : -> Id .
 op intruder : Rat Nat -> Intruder .
 eq intruder(ff,n) 
   = [iid : intruder |
      (v2vMsgs : genMsgs(ff,n,none))
      (blockActSndSet : { v(0) ; true ; 0} )
      ] .

 op asysint : Rat Nat -> ASystemIntruder .
 eq asysint(ff, n) 
  = {simple-scenario ; intruder(ff,n)} .

 op bad-state : ASystemIntruder -> Bool .
 op bad-state$ : Agent -> Bool .

 ceq bad-state({ {conf agent} ; int})
 = true 
 if bad-state$(agent) .
 eq bad-state$([id0 : cl |
     (lkb : ((gapNext(id0, ff) @ t0)
           (speed(id0,ff1) @ t1)
           gapSafety(id0,ffL,ffH) kb)), 
     attrs ]) = ff < ffL * ff1 .
 
 op bad-state2 : Rat ASystemIntruder -> Bool .
 op bad-state2$ : Rat Agent -> Bool .
 ceq bad-state2(ff1,{ {conf agent} ; int})
  = true 
  if bad-state2$(ff1,agent) .
 eq bad-state2$(ff1,[id0 : cl |
  (lkb : ((gapNext(id0, ff) @ t0) kb)), 
  attrs ]) = ff < ff1 .

 op crash : ASystemIntruder -> Bool .
 op crash$ : Env -> Bool .
 ceq crash({ {conf env} ; int})
  = true 
  if crash$(env) .

  eq crash$([id0 |
   (atloc(v(1), loc(ff1)) @ t1)
   (atloc(v(0), loc(ff0)) @ t0) 
    kb]) = ff1 >= ff0 .

 op plCkLogs : ASystemIntruder -> Bool .
 op plCkLogs$ : Env -> Bool .
 ceq plCkLogs({ {conf env} ; int})
  = true 
  if plCkLogs$(env) .

  eq plCkLogs$([id0 |
   (logSpdPlCkFail(v(1),v(0),n) @ t0)
    kb]) = n == 0 .

 op asys2 : -> ASystemIntruder .

op getAgtFromConf : ASystemIntruder -> Agent .
eq getAgtFromConf({ { agent1 agent2 conf env } ; int }) = agent2 .

op noLogs : ASystemIntruder -> Bool .
op noLogs$ : Agent -> Bool .
 
ceq noLogs({ scario ; int})
 = true 
 if noLogs$(getAgtFromConf({ scario ; int})) .

ceq noLogs$( [v(1) : cl | 
            lkb : kb0,
            ckb : none,
            sensors : (locS speedS gapS), 
            evs : evs ] 
             )
= if ( (cnt == 0) )  then
    true
  else
    false
  fi 
if (logSpdPlCkFail(v(1), v(0), cnt) @ t1) kb := kb0 .
endm

eof

search [1] in TEST-INTRUDER : asysint(70, 1) =>* iasys such that crash(iasys) and noLogs(iasys) .


*** *** new load; without plausibility check enabled ***
search [1] in TEST-INTRUDER : asysint(70, 1) =>* iasys such that crash(iasys) = true .

Solution 1 (state 15350)
states: 15351  rewrites: 1905043 in 2048ms cpu (2046ms real) (930196 rewrites/second)
iasys --> {{
[eId |
  clock(14) class(v(0), veh) class(v(1), veh) class(i(0), infra) (atloc(v(0), loc(778)) @ 14) (atloc(v(1), loc(778)) @ 14) (speed(v(0), 22) @ 14) (speed(v(1), 21) @ 14) (accel(v(0), 0) @ 14) accel(v(1),
    0) @ 14] 
[v(0) : veh |
  lkb : (clock(14) class(v(0), veh) (lastAct(actSpeed(v(0), 19, 25)) @ 13) (atloc(v(0), loc(756)) @ 13) (atloc(v(1), loc(730)) @ 12) (mode(v(0), leading(none)) @ 0) (platoon(v(0), v(1)) @ 0) (speed(v(0),
    22) @ 13) (speed(v(1), 25) @ 12) maxAcc(v(0), 3)),
  ckb : none,
  sensors : (locS speedS gapS),
  evs : ((tick @ 0) v2v(v(0), msg(v(1), v(0), hbf2l(v(1), 23, loc(755))) @ 13) @ 0)] 
[v(1) : veh |
  lkb : (clock(14) class(v(1), veh) (lastAct(actSpeed(v(1), 20, 71/3)) @ 13) (atloc(v(0), loc(2070)) @ 3) (atloc(v(1), loc(755)) @ 13) (mode(v(1), following(v(0))) @ 0) (platoon(v(0), v(1)) @ 0) (
    histGap(v(1), (1 @ 13) ; (4 @ 12) ; 9 @ 11) @ 13) (speed(v(0), 70) @ 3) (speed(v(1), 23) @ 13) (gapNext(v(1), 1) @ 13) (idNext(v(1), v(0)) @ 0) (logSpdPlCkFail(v(1), v(0), 0) @ 0) (histSpd(v(1), v(
    0), (70 @ 3) ; (22 @ 2) ; 22 @ 1) @ 3) maxAcc(v(1), 3) gapGreen(v(1), 1, 3) gapSafety(v(1), 2, 4)),
  ckb : none,
  sensors : (locS speedS gapS),
  evs : (tick @ 0)] 
[i(0) : infra |
  lkb : (clock(14) (atloc(v(0), loc(756)) @ 13) atloc(v(1), loc(755)) @ 13),
  ckb : none,
  sensors : vehS,
  evs : (tick @ 0)]} ; 
[iid : intruder |
  v2vMsgs : none
  blockActSndSet : {v(0) ; true ; 0}]}


*** without plausibility check enabled and # blocked messaged enabled ***
search [1] in TEST-INTRUDER : asysint(70, 1) =>* iasys such that crash(iasys) = true .

Solution 1 (state 121827)
states: 121828  rewrites: 112596834 in 181688ms cpu (181689ms real) (619726 rewrites/second)
iasys --> {{
[eId |
  clock(10) class(v(0), veh) class(v(1), veh) class(v(2), veh) class(i(0), infra) (atloc(v(0), loc(1200)) @ 10) (atloc(v(1), loc(1201)) @ 10) (atloc(v(2), loc(350)) @ 10) (speed(v(0), 20) @ 10) (speed(v(
    1), 20) @ 10) (speed(v(2), 25) @ 0) (accel(v(0), 0) @ 10) (accel(v(1), 0) @ 10) accel(v(2), 0) @ 0] 
[v(0) : veh |
  lkb : (clock(10) class(v(0), veh) (lastAct(actSpeed(v(0), 17, 23)) @ 9) (atloc(v(0), loc(1180)) @ 9) (atloc(v(1), loc(1152)) @ 8) (mode(v(0), leading(none)) @ 0) (platoon(v(0), v(1)) @ 0) (speed(v(0),
    20) @ 9) (speed(v(1), 26) @ 8) maxAcc(v(0), 3)),
  ckb : none,
  sensors : (locS speedS gapS),
  evs : ((tick @ 0) v2v(v(0), msg(v(1), v(0), hbf2l(v(1), 23, loc(1178))) @ 9) @ 0)] 
[v(1) : veh |
  lkb : (clock(10) class(v(1), veh) (lastAct(actSpeed(v(1), 20, 20)) @ 9) (atloc(v(0), loc(1160)) @ 8) (atloc(v(1), loc(1178)) @ 9) (mode(v(1), following(v(0))) @ 0) (platoon(v(0), v(1)) @ 0) (histGap(v(
    1), (2 @ 9) ; (8 @ 8) ; 17 @ 7) @ 9) (speed(v(0), 20) @ 8) (speed(v(1), 23) @ 9) (gapNext(v(1), 2) @ 9) (idNext(v(1), v(0)) @ 0) 
  (logSpdPlCkFail(v(1), v(0), 0) @ 0) (histSpd(v(1), v(0), (20 @ 8) ; (20 @ 7) ; 20 @ 6) @ 8) maxAcc(v(1), 3) gapGreen(v(1), 1, 3) gapSafety(v(1), 2, 4)),
  ckb : none,
  sensors : (locS speedS gapS),
  evs : ((tick @ 0) v2v(v(1), msg(v(0), v(1), hbl2f(v(0), 20, loc(1180), (atloc(v(1), loc(1152)) @ 8) (platoon(v(0), v(1)) @ 0) speed(v(1), 26) @ 8)) @ 9) @ 0)] 
[i(0) : infra |
  lkb : (clock(10) (atloc(v(0), loc(1180)) @ 9) (atloc(v(1), loc(1178)) @ 9) (atloc(v(2), loc(325)) @ 9) (i2vTrigger(i(0), v(2), 500, 50, nuPlatoon) @ 0) i2vTrigger(i(0), v(2), 600, 50, join(v(0))) @ 0),
  ckb : none,
  sensors : vehS,
  evs : (tick @ 0)]} ; 
[iid : intruder |
  v2vMsgs : none
  blockActSnd : v(0) ; 5]}


*** with plausibility check enabled and # blocked messaged enabled ***
search [1] in TEST-INTRUDER : asysint(70, 1) =>* iasys such that crash(iasys) = true .
Solution 1 (state 143395)
states: 143396  rewrites: 131789003 in 177772ms cpu (177782ms real) (741337 rewrites/second)
iasys --> {{
[eId |
  clock(10) class(v(0), veh) class(v(1), veh) class(v(2), veh) class(i(0), infra) (atloc(v(0), loc(1200)) @ 10) (atloc(v(1), loc(1201)) @ 10) (atloc(v(2), loc(350)) @ 10) (speed(v(0), 20) @ 10) (speed(v(
    1), 20) @ 10) (speed(v(2), 25) @ 0) (accel(v(0), 0) @ 10) (accel(v(1), 0) @ 10) accel(v(2), 0) @ 0] 
[v(0) : veh |
  lkb : (clock(10) class(v(0), veh) (lastAct(actSpeed(v(0), 17, 23)) @ 9) (atloc(v(0), loc(1180)) @ 9) (atloc(v(1), loc(1152)) @ 8) (mode(v(0), leading(none)) @ 0) (platoon(v(0), v(1)) @ 0) (speed(v(0),
    20) @ 9) (speed(v(1), 26) @ 8) maxAcc(v(0), 3)),
  ckb : none,
  sensors : (locS speedS gapS),
  evs : ((tick @ 0) v2v(v(0), msg(v(1), v(0), hbf2l(v(1), 23, loc(1178))) @ 9) @ 0)] 
[v(1) : veh |
  lkb : (clock(10) class(v(1), veh) (lastAct(actSpeed(v(1), 20, 20)) @ 9) (atloc(v(0), loc(1160)) @ 8) (atloc(v(1), loc(1178)) @ 9) (mode(v(1), following(v(0))) @ 0) (platoon(v(0), v(1)) @ 0) (histGap(v(
    1), (2 @ 9) ; (8 @ 8) ; 17 @ 7) @ 9) (speed(v(0), 20) @ 8) (speed(v(1), 23) @ 9) (gapNext(v(1), 2) @ 9) (idNext(v(1), v(0)) @ 0) 
  (logSpdPlCkFail(v(1), v(0), 8) @ 9) (histSpd(v(1), v(0), (20 @ 8) ; (20 @ 7) ; 20 @ 6) @ 8) maxAcc(v(1), 3) gapGreen(v(1), 1, 3) gapSafety(v(1), 2, 4)),
  ckb : none,
  sensors : (locS speedS gapS),
  evs : ((tick @ 0) v2v(v(1), msg(v(0), v(1), hbl2f(v(0), 20, loc(1180), (atloc(v(1), loc(1152)) @ 8) (platoon(v(0), v(1)) @ 0) speed(v(1), 26) @ 8)) @ 9) @ 0)] 
[i(0) : infra |
  lkb : (clock(10) (atloc(v(0), loc(1180)) @ 9) (atloc(v(1), loc(1178)) @ 9) (atloc(v(2), loc(325)) @ 9) (i2vTrigger(i(0), v(2), 500, 50, nuPlatoon) @ 0) i2vTrigger(i(0), v(2), 600, 50, join(v(0))) @ 0),
  ckb : none,
  sensors : vehS,
  evs : (tick @ 0)]} ; 
[iid : intruder |
  v2vMsgs : none
  blockActSnd : v(0) ; 5]}



*** with plausibility check enabled ***
search [1] in TEST-INTRUDER : asysint(70, 1) =>* iasys such that crash(iasys) = true .

Solution 1 (state 52774)
states: 52775  rewrites: 71375582 in 72476ms cpu (72475ms real) (984816 rewrites/second)
iasys --> {{
[eId |
  clock(9) class(v(0), veh) class(v(1), veh) class(v(2), veh) class(i(0), infra) (atloc(v(0), loc(1180)) @ 9) (atloc(v(1), loc(1181)) @ 9) (atloc(v(2), loc(325)) @ 9) (speed(v(0), 20) @ 9) (speed(v(1),
    20) @ 9) (speed(v(2), 25) @ 0) (accel(v(0), 0) @ 9) (accel(v(1), 0) @ 9) accel(v(2), 0) @ 0] 
[v(0) : veh |
  lkb : (clock(9) class(v(0), veh) (lastAct(actSpeed(v(0), 17, 23)) @ 8) (atloc(v(0), loc(1160)) @ 8) (atloc(v(1), loc(1132)) @ 7) (mode(v(0), leading(v(1))) @ 0) (platoon(v(0), v(1)) @ 0) (speed(v(0),
    20) @ 8) (speed(v(1), 26) @ 7) maxAcc(v(0), 3)),
  ckb : none,
  sensors : (locS speedS gapS),
  evs : ((tick @ 0) v2v(v(0), msg(v(1), v(0), hbf2l(v(1), 23, loc(1158))) @ 8) @ 0)] 
[v(1) : veh |
  lkb : (clock(9) class(v(1), veh) (lastAct(actSpeed(v(1), 20, 20)) @ 8) (atloc(v(0), loc(1140)) @ 7) (atloc(v(1), loc(1158)) @ 8) (mode(v(1), following(v(0))) @ 0) (platoon(v(0), v(1)) @ 0) (histGap(v(
    1), (2 @ 8) ; (8 @ 7) ; 17 @ 6) @ 8) (speed(v(0), 20) @ 7) (speed(v(1), 23) @ 8) (gapNext(v(1), 2) @ 8) (idNext(v(1), v(0)) @ 0) (logSpdPlCkFail(v(1), v(0), 2) @ 8) (histSpd(v(1), v(0), (20 @ 7) ; (
    20 @ 6) ; 20 @ 5) @ 7) maxAcc(v(1), 3) gapGreen(v(1), 1, 3) gapSafety(v(1), 2, 4)),
  ckb : none,
  sensors : (locS speedS gapS),
  evs : ((tick @ 0) (v2v(v(1), msg(v(0), v(1), hbl2f(v(0), 20, loc(1160), (atloc(v(1), loc(1132)) @ 7) (platoon(v(0), v(1)) @ 0) speed(v(1), 26) @ 7)) @ 8) @ 0) v2v(v(1), msg(v(0), v(1), hbl2j(v(0), v(
    1), 26, loc(1132))) @ 8) @ 0)] 
[i(0) : infra |
  lkb : (clock(9) (atloc(v(0), loc(1160)) @ 8) (atloc(v(1), loc(1158)) @ 8) (atloc(v(2), loc(300)) @ 8) (i2vTrigger(i(0), v(2), 500, 50, nuPlatoon) @ 0) i2vTrigger(i(0), v(2), 600, 50, join(v(0))) @ 0),
  ckb : none,
  sensors : vehS,
  evs : (tick @ 0)]} ; 
[iid : intruder |
  v2vMsgs : none
  blockActSnd : v(0)]}

*** with plausibility check disabled ***
search [1] in TEST-INTRUDER : asysint(70, 1) =>* iasys such that crash(iasys) = true .
*** search [1] in TEST-INTRUDER : asysint(70, 1) =>* iasys such that crash(iasys) = true and plCkLogs(iasys) .

Solution 1 (state 37805)
states: 37806  rewrites: 49850987 in 65568ms cpu (65908ms real) (760288 rewrites/second)
iasys --> {{
[eId |
  clock(9) class(v(0), veh) class(v(1), veh) class(v(2), veh) class(i(0), infra) (atloc(v(0), loc(1180)) @ 9) (atloc(v(1), loc(1181)) @ 9) (
    atloc(v(2), loc(325)) @ 9) (speed(v(0), 20) @ 9) (speed(v(1), 20) @ 9) (speed(v(2), 25) @ 0) (accel(v(0), 0) @ 9) (accel(v(1), 0) @ 9) accel(
    v(2), 0) @ 0]
[v(0) : veh |
  lkb : (clock(9) class(v(0), veh) (lastAct(actSpeed(v(0), 17, 23)) @ 8) (atloc(v(0), loc(1160)) @ 8) (atloc(v(1), loc(1132)) @ 7) (mode(v(0),
    leading(v(1))) @ 0) (platoon(v(0), v(1)) @ 0) (speed(v(0), 20) @ 8) (speed(v(1), 26) @ 7) maxAcc(v(0), 3)),
  ckb : none,
  sensors : (locS speedS gapS),
  evs : ((tick @ 0) v2v(v(0), msg(v(1), v(0), hbf2l(v(1), 23, loc(1158))) @ 8) @ 0)]
[v(1) : veh |
  lkb : (clock(9) class(v(1), veh) (lastAct(actSpeed(v(1), 20, 20)) @ 8) (atloc(v(0), loc(1140)) @ 7) (atloc(v(1), loc(1158)) @ 8) (mode(v(1),
    following(v(0))) @ 0) (platoon(v(0), v(1)) @ 0) (histGap(v(1), (2 @ 8) ; (8 @ 7) ; 17 @ 6) @ 8) (speed(v(0), 20) @ 7) (speed(v(1), 23) @ 8) (
    gapNext(v(1), 2) @ 8) (idNext(v(1), v(0)) @ 0) (histSpd(v(1), v(0), (20 @ 7) ; (20 @ 6) ; 20 @ 5) @ 7) maxAcc(v(1), 3) gapGreen(v(1), 1, 3)
    gapSafety(v(1), 2, 4)),
  ckb : none,
  sensors : (locS speedS gapS),
  evs : ((tick @ 0) (v2v(v(1), msg(v(0), v(1), hbl2f(v(0), 20, loc(1160), (atloc(v(1), loc(1132)) @ 7) (platoon(v(0), v(1)) @ 0) speed(v(1), 26)
    @ 7)) @ 8) @ 0) v2v(v(1), msg(v(0), v(1), hbl2j(v(0), v(1), 26, loc(1132))) @ 8) @ 0)]
[i(0) : infra |
  lkb : (clock(9) (atloc(v(0), loc(1160)) @ 8) (atloc(v(1), loc(1158)) @ 8) (atloc(v(2), loc(300)) @ 8) (i2vTrigger(i(0), v(2), 500, 50,
    nuPlatoon) @ 0) i2vTrigger(i(0), v(2), 600, 50, join(v(0))) @ 0),
  ckb : none,
  sensors : vehS,
  evs : (tick @ 0)]} ;
[iid : intruder |
  v2vMsgs : none
  blockActSnd : v(0)]}

search [1] in TEST-INTRUDER : asysint(100, 1) =>* iasys such that crash(iasys) = true .

Solution 1 (state 12336)
states: 12337  rewrites: 15812129 in 20147ms cpu (20257ms real) (784827 rewrites/second)
iasys --> {{
[eId |
  clock(7) class(v(0), veh) class(v(1), veh) class(v(2), veh) class(i(0), infra) (atloc(v(0), loc(1140)) @ 7) (atloc(v(1), loc(1140)) @ 7) (
    atloc(v(2), loc(275)) @ 7) (speed(v(0), 20) @ 7) (speed(v(1), 28) @ 7) (speed(v(2), 25) @ 0) (accel(v(0), 0) @ 7) (accel(v(1), 0) @ 7) accel(
    v(2), 0) @ 0]
[v(0) : veh |
  lkb : (clock(7) class(v(0), veh) (lastAct(actSpeed(v(0), 17, 23)) @ 6) (atloc(v(0), loc(1120)) @ 6) (atloc(v(1), loc(1075)) @ 5) (mode(v(0),
    leading(v(1))) @ 0) (platoon(v(0), v(1)) @ 0) (speed(v(0), 20) @ 6) (speed(v(1), 34) @ 5) maxAcc(v(0), 3)),
  ckb : none,
  sensors : (locS speedS gapS),
  evs : ((tick @ 0) v2v(v(0), msg(v(1), v(0), hbf2l(v(1), 31, loc(1109))) @ 6) @ 0)]
[v(1) : veh |
  lkb : (clock(7) class(v(1), veh) (lastAct(actSpeed(v(1), 28, 28)) @ 6) (atloc(v(0), loc(1100)) @ 5) (atloc(v(1), loc(1109)) @ 6) (mode(v(1),
    following(v(0))) @ 0) (platoon(v(0), v(1)) @ 0) (histGap(v(1), (11 @ 6) ; (25 @ 5) ; 37 @ 4) @ 6) (speed(v(0), 20) @ 5) (speed(v(1), 31) @ 6)
    (gapNext(v(1), 11) @ 6) (idNext(v(1), v(0)) @ 0) (histSpd(v(1), v(0), (20 @ 5) ; (20 @ 4) ; 100 @ 0) @ 5) maxAcc(v(1), 3) gapGreen(v(1), 1,
    3) gapSafety(v(1), 2, 4)),
  ckb : none,
  sensors : (locS speedS gapS),
  evs : ((tick @ 0) (v2v(v(1), msg(v(0), v(1), hbl2f(v(0), 20, loc(1120), (atloc(v(1), loc(1075)) @ 5) (platoon(v(0), v(1)) @ 0) speed(v(1), 34)
    @ 5)) @ 6) @ 0) v2v(v(1), msg(v(0), v(1), hbl2j(v(0), v(1), 34, loc(1075))) @ 6) @ 0)]
[i(0) : infra |
  lkb : (clock(7) (atloc(v(0), loc(1120)) @ 6) (atloc(v(1), loc(1109)) @ 6) (atloc(v(2), loc(250)) @ 6) (i2vTrigger(i(0), v(2), 500, 50,
    nuPlatoon) @ 0) i2vTrigger(i(0), v(2), 600, 50, join(v(0))) @ 0),
  ckb : none,
  sensors : vehS,
  evs : (tick @ 0)]} ;
[iid : intruder |
  v2vMsgs : none
  blockActSnd : v(0)]}



search[1] asysint(60,1) =>* iasys such that bad-state2(40,iasys) .
Solution 1 (state 1423)
states: 1424  rewrites: 1734212 in 1990ms cpu (1993ms real) (871342 rewrites/second)
iasys --> {{
[eId |
  clock(4) class(v(0), veh) class(v(1), veh) class(v(2), veh) class(i(0), infra) (atloc(v(0), loc(1080)) @ 4) (atloc(v(1), loc(1042)) @ 4) (
    atloc(v(2), loc(200)) @ 4) (speed(v(0), 20) @ 4) (speed(v(1), 25) @ 4) (speed(v(2), 25) @ 0) (accel(v(0), 0) @ 4) (accel(v(1), 0) @ 4) accel(
    v(2), 0) @ 0]
[v(0) : veh |
  lkb : (clock(4) class(v(0), veh) (lastAct(actSpeed(v(0), 17, 23)) @ 3) (atloc(v(0), loc(1060)) @ 3) (atloc(v(1), loc(988)) @ 2) (mode(v(0),
    leading(v(1))) @ 0) (platoon(v(0), v(1)) @ 0) (speed(v(0), 20) @ 3) (speed(v(1), 26) @ 2) maxAcc(v(0), 3)),
  ckb : none,
  sensors : (locS speedS gapS),
  evs : ((tick @ 0) v2v(v(0), msg(v(1), v(0), hbf2l(v(1), 28, loc(1014))) @ 3) @ 0)]
[v(1) : veh |
  lkb : (clock(4) class(v(1), veh) (lastAct(actSpeed(v(1), 22, 22)) @ 4) (atloc(v(0), loc(1060)) @ 3) (atloc(v(1), loc(1042)) @ 4) (mode(v(1),
    following(v(0))) @ 0) (platoon(v(0), v(1)) @ 0) (histGap(v(1), (38 @ 4) ; (46 @ 3) ; 52 @ 2) @ 4) (speed(v(0), 20) @ 3) (speed(v(1), 25) @ 4)
    (gapNext(v(1), 38) @ 4) (idNext(v(1), v(0)) @ 0) (histSpd(v(1), v(0), (20 @ 3) ; (20 @ 2) ; 60 @ 0) @ 3) maxAcc(v(1), 3) gapGreen(v(1), 1, 3)
    gapSafety(v(1), 2, 4)),
  ckb : none,
  sensors : (locS speedS gapS),
  evs : ((tick @ 1) (actSnd(v(1), msg(v(1), v(0), hbf2l(v(1), 25, loc(1042))) @ 4) @ 0) {u(1),actSpeed(v(1), 22, 22)} @ 0)]
[i(0) : infra |
  lkb : (clock(4) (atloc(v(0), loc(1060)) @ 3) (atloc(v(1), loc(1014)) @ 3) (atloc(v(2), loc(175)) @ 3) (i2vTrigger(i(0), v(2), 500, 50,
    nuPlatoon) @ 0) i2vTrigger(i(0), v(2), 600, 50, join(v(0))) @ 0),
  ckb : none,
  sensors : vehS,
  evs : (tick @ 0)]} ;
[iid : intruder |
  v2vMsgs : none
  blockActSnd : v(0)]}

search[1] asysint(60,1) =>* iasys such that bad-state2(30,iasys) .

Solution 1 (state 6852)
states: 6853  rewrites: 8631075 in 10756ms cpu (10796ms real) (802383 rewrites/second)
iasys --> {{
[eId |
  clock(6) class(v(0), veh) class(v(1), veh) class(v(2), veh) class(i(0), infra) (atloc(v(0), loc(1120)) @ 6) (atloc(v(1), loc(1095)) @ 6) (
    atloc(v(2), loc(250)) @ 6) (speed(v(0), 20) @ 6) (speed(v(1), 22) @ 6) (speed(v(2), 25) @ 0) (accel(v(0), 0) @ 6) (accel(v(1), 0) @ 6) accel(
    v(2), 0) @ 0]
[v(0) : veh |
  lkb : (clock(6) class(v(0), veh) (lastAct(actSpeed(v(0), 17, 23)) @ 5) (atloc(v(0), loc(1100)) @ 5) (atloc(v(1), loc(1042)) @ 4) (mode(v(0),
    leading(v(1))) @ 0) (platoon(v(0), v(1)) @ 0) (speed(v(0), 20) @ 5) (speed(v(1), 28) @ 4) maxAcc(v(0), 3)),
  ckb : none,
  sensors : (locS speedS gapS),
  evs : ((tick @ 0) v2v(v(0), msg(v(1), v(0), hbf2l(v(1), 25, loc(1070))) @ 5) @ 0)]
[v(1) : veh |
  lkb : (clock(6) class(v(1), veh) (lastAct(actSpeed(v(1), 19, 19)) @ 6) (atloc(v(0), loc(1100)) @ 5) (atloc(v(1), loc(1095)) @ 6) (mode(v(1),
    following(v(0))) @ 0) (platoon(v(0), v(1)) @ 0) (histGap(v(1), (25 @ 6) ; (30 @ 5) ; 38 @ 4) @ 6) (speed(v(0), 20) @ 5) (speed(v(1), 22) @ 6)
    (gapNext(v(1), 25) @ 6) (idNext(v(1), v(0)) @ 0) (histSpd(v(1), v(0), (20 @ 5) ; (20 @ 4) ; 20 @ 3) @ 5) maxAcc(v(1), 3) gapGreen(v(1), 1, 3)
    gapSafety(v(1), 2, 4)),
  ckb : none,
  sensors : (locS speedS gapS),
  evs : ((tick @ 1) (actSnd(v(1), msg(v(1), v(0), hbf2l(v(1), 22, loc(1095))) @ 6) @ 0) {u(1),actSpeed(v(1), 19, 19)} @ 0)]
[i(0) : infra |
  lkb : (clock(6) (atloc(v(0), loc(1100)) @ 5) (atloc(v(1), loc(1070)) @ 5) (atloc(v(2), loc(225)) @ 5) (i2vTrigger(i(0), v(2), 500, 50,
    nuPlatoon) @ 0) i2vTrigger(i(0), v(2), 600, 50, join(v(0))) @ 0),
  ckb : none,
  sensors : vehS,
  evs : (tick @ 0)]} ;
[iid : intruder |
  v2vMsgs : none
  blockActSnd : v(0)]}


search[1] asysint(60,1) =>* iasys such that bad-state2(20,iasys) .
Solution 1 (state 14084)
states: 14085  rewrites: 18125130 in 21749ms cpu (21823ms real) (833355 rewrites/second)
iasys --> {{
[eId |
  clock(7) class(v(0), veh) class(v(1), veh) class(v(2), veh) class(i(0), infra) (atloc(v(0), loc(1140)) @ 7) (atloc(v(1), loc(1123)) @ 7) (
    atloc(v(2), loc(275)) @ 7) (speed(v(0), 20) @ 7) (speed(v(1), 22) @ 7) (speed(v(2), 25) @ 0) (accel(v(0), 0) @ 7) (accel(v(1), 0) @ 7) accel(
    v(2), 0) @ 0]
[v(0) : veh |
  lkb : (clock(7) class(v(0), veh) (lastAct(actSpeed(v(0), 17, 23)) @ 6) (atloc(v(0), loc(1120)) @ 6) (atloc(v(1), loc(1070)) @ 5) (mode(v(0),
    leading(v(1))) @ 0) (platoon(v(0), v(1)) @ 0) (speed(v(0), 20) @ 6) (speed(v(1), 28) @ 5) maxAcc(v(0), 3)),
  ckb : none,
  sensors : (locS speedS gapS),
  evs : ((tick @ 0) v2v(v(0), msg(v(1), v(0), hbf2l(v(1), 25, loc(1098))) @ 6) @ 0)]
[v(1) : veh |
  lkb : (clock(7) class(v(1), veh) (lastAct(actSpeed(v(1), 19, 19)) @ 7) (atloc(v(0), loc(1120)) @ 6) (atloc(v(1), loc(1123)) @ 7) (mode(v(1),
    following(v(0))) @ 0) (platoon(v(0), v(1)) @ 0) (histGap(v(1), (17 @ 7) ; (22 @ 6) ; 30 @ 5) @ 7) (speed(v(0), 20) @ 6) (speed(v(1), 22) @ 7)
    (gapNext(v(1), 17) @ 7) (idNext(v(1), v(0)) @ 0) (histSpd(v(1), v(0), (20 @ 6) ; (20 @ 5) ; 20 @ 4) @ 6) maxAcc(v(1), 3) gapGreen(v(1), 1, 3)
    gapSafety(v(1), 2, 4)),
  ckb : none,
  sensors : (locS speedS gapS),
  evs : ((tick @ 1) (actSnd(v(1), msg(v(1), v(0), hbf2l(v(1), 22, loc(1123))) @ 7) @ 0) {u(1),actSpeed(v(1), 19, 19)} @ 0)]
[i(0) : infra |
  lkb : (clock(7) (atloc(v(0), loc(1120)) @ 6) (atloc(v(1), loc(1098)) @ 6) (atloc(v(2), loc(250)) @ 6) (i2vTrigger(i(0), v(2), 500, 50,
    nuPlatoon) @ 0) i2vTrigger(i(0), v(2), 600, 50, join(v(0))) @ 0),
  ckb : none,
  sensors : vehS,
  evs : (tick @ 0)]} ;
[iid : intruder |
  v2vMsgs : none
  blockActSnd : v(0)]}

search[1] asysint(40,1) =>* iasys such that bad-state(iasys) .
Solution 1 (state 628)
states: 629  rewrites: 749688 in 820ms cpu (820ms real) (913844 rewrites/second)
iasys --> {{
[eId |
  clock(3) class(v(0), veh) class(v(1), veh) class(v(2), veh) class(i(0), infra) (atloc(v(0), loc(1060)) @ 3) (atloc(v(1), loc(1012)) @ 3) (
    atloc(v(2), loc(175)) @ 3) (speed(v(0), 20) @ 3) (speed(v(1), 25) @ 3) (speed(v(2), 25) @ 0) (accel(v(0), 0) @ 3) (accel(v(1), 0) @ 3) accel(
    v(2), 0) @ 0]
[v(0) : veh |
  lkb : (clock(3) class(v(0), veh) (lastAct(actSpeed(v(0), 17, 23)) @ 2) (atloc(v(0), loc(1040)) @ 2) (atloc(v(1), loc(965)) @ 1) (mode(v(0),
    leading(v(1))) @ 0) (platoon(v(0), v(1)) @ 0) (speed(v(0), 20) @ 2) (speed(v(1), 23) @ 1) maxAcc(v(0), 3)),
  ckb : none,
  sensors : (locS speedS gapS),
  evs : ((tick @ 0) v2v(v(0), msg(v(1), v(0), hbf2l(v(1), 24, loc(988))) @ 2) @ 0)]
[v(1) : veh |
  lkb : (clock(3) class(v(1), veh) (lastAct(actSpeed(v(1), 22, 68/3)) @ 3) (atloc(v(0), loc(1040)) @ 2) (atloc(v(1), loc(1012)) @ 3) (mode(v(1),
    following(v(0))) @ 0) (platoon(v(0), v(1)) @ 0) (histGap(v(1), (48 @ 3) ; (52 @ 2) ; 55 @ 1) @ 3) (speed(v(0), 20) @ 2) (speed(v(1), 25) @ 3)
    (gapNext(v(1), 48) @ 3) (idNext(v(1), v(0)) @ 0) (histSpd(v(1), v(0), (20 @ 2) ; (40 @ 0) ; noVal) @ 2) maxAcc(v(1), 3) gapGreen(v(1), 1, 3)
    gapSafety(v(1), 2, 4)),
  ckb : none,
  sensors : (locS speedS gapS),
  evs : ((tick @ 1) (actSnd(v(1), msg(v(1), v(0), hbf2l(v(1), 25, loc(1012))) @ 3) @ 0) {u(1),actSpeed(v(1), 22, 68/3)} @ 0)]
[i(0) : infra |
  lkb : (clock(3) (atloc(v(0), loc(1040)) @ 2) (atloc(v(1), loc(988)) @ 2) (atloc(v(2), loc(150)) @ 2) (i2vTrigger(i(0), v(2), 500, 50,
    nuPlatoon) @ 0) i2vTrigger(i(0), v(2), 600, 50, join(v(0))) @ 0),
  ckb : none,
  sensors : vehS,
  evs : (tick @ 0)]} ;
[iid : intruder |
  v2vMsgs : none
  blockActSnd : v(0)]}

search[1] asysint(50,1) =>* iasys such that bad-state(iasys) .
Solution 1 (state 628)
states: 629  rewrites: 749612 in 828ms cpu (828ms real) (905196 rewrites/second)
iasys --> {{
[eId |
  clock(3) class(v(0), veh) class(v(1), veh) class(v(2), veh) class(i(0), infra) (atloc(v(0), loc(1060)) @ 3) (atloc(v(1), loc(1014)) @ 3) (
    atloc(v(2), loc(175)) @ 3) (speed(v(0), 20) @ 3) (speed(v(1), 27) @ 3) (speed(v(2), 25) @ 0) (accel(v(0), 0) @ 3) (accel(v(1), 0) @ 3) accel(
    v(2), 0) @ 0]
[v(0) : veh |
  lkb : (clock(3) class(v(0), veh) (lastAct(actSpeed(v(0), 17, 23)) @ 2) (atloc(v(0), loc(1040)) @ 2) (atloc(v(1), loc(965)) @ 1) (mode(v(0),
    leading(v(1))) @ 0) (platoon(v(0), v(1)) @ 0) (speed(v(0), 20) @ 2) (speed(v(1), 23) @ 1) maxAcc(v(0), 3)),
  ckb : none,
  sensors : (locS speedS gapS),
  evs : ((tick @ 0) v2v(v(0), msg(v(1), v(0), hbf2l(v(1), 26, loc(988))) @ 2) @ 0)]
[v(1) : veh |
  lkb : (clock(3) class(v(1), veh) (lastAct(actSpeed(v(1), 24, 24)) @ 3) (atloc(v(0), loc(1040)) @ 2) (atloc(v(1), loc(1014)) @ 3) (mode(v(1),
    following(v(0))) @ 0) (platoon(v(0), v(1)) @ 0) (histGap(v(1), (46 @ 3) ; (52 @ 2) ; 55 @ 1) @ 3) (speed(v(0), 20) @ 2) (speed(v(1), 27) @ 3)
    (gapNext(v(1), 46) @ 3) (idNext(v(1), v(0)) @ 0) (histSpd(v(1), v(0), (20 @ 2) ; (50 @ 0) ; noVal) @ 2) maxAcc(v(1), 3) gapGreen(v(1), 1, 3)
    gapSafety(v(1), 2, 4)),
  ckb : none,
  sensors : (locS speedS gapS),
  evs : ((tick @ 1) (actSnd(v(1), msg(v(1), v(0), hbf2l(v(1), 27, loc(1014))) @ 3) @ 0) {u(1),actSpeed(v(1), 24, 24)} @ 0)]
[i(0) : infra |
  lkb : (clock(3) (atloc(v(0), loc(1040)) @ 2) (atloc(v(1), loc(988)) @ 2) (atloc(v(2), loc(150)) @ 2) (i2vTrigger(i(0), v(2), 500, 50,
    nuPlatoon) @ 0) i2vTrigger(i(0), v(2), 600, 50, join(v(0))) @ 0),
  ckb : none,
  sensors : vehS,
  evs : (tick @ 0)]} ;
[iid : intruder |
  v2vMsgs : none
  blockActSnd : v(0)]}

search[1] asysint(60,1) =>* iasys such that bad-state2(10,iasys) .

Solution 1 (state 46552)
states: 46553  rewrites: 61293115 in 74142ms cpu (74293ms real) (826694 rewrites/second)
iasys --> {{
[eId |
  clock(9) class(v(0), veh) class(v(1), veh) class(v(2), veh) class(i(0), infra) (atloc(v(0), loc(1180)) @ 9) (atloc(v(1), loc(1172)) @ 9) (
    atloc(v(2), loc(325)) @ 9) (speed(v(0), 20) @ 9) (speed(v(1), 19) @ 9) (speed(v(2), 25) @ 0) (accel(v(0), 0) @ 9) (accel(v(1), 0) @ 9) accel(
    v(2), 0) @ 0]
[v(0) : veh |
  lkb : (clock(9) class(v(0), veh) (lastAct(actSpeed(v(0), 17, 23)) @ 8) (atloc(v(0), loc(1160)) @ 8) (atloc(v(1), loc(1125)) @ 7) (mode(v(0),
    leading(v(1))) @ 0) (platoon(v(0), v(1)) @ 0) (speed(v(0), 20) @ 8) (speed(v(1), 25) @ 7) maxAcc(v(0), 3)),
  ckb : none,
  sensors : (locS speedS gapS),
  evs : ((tick @ 0) v2v(v(0), msg(v(1), v(0), hbf2l(v(1), 22, loc(1150))) @ 8) @ 0)]
[v(1) : veh |
  lkb : (clock(9) class(v(1), veh) (lastAct(actSpeed(v(1), 16, 16)) @ 9) (atloc(v(0), loc(1160)) @ 8) (atloc(v(1), loc(1172)) @ 9) (mode(v(1),
    following(v(0))) @ 0) (platoon(v(0), v(1)) @ 0) (histGap(v(1), (8 @ 9) ; (10 @ 8) ; 15 @ 7) @ 9) (speed(v(0), 20) @ 8) (speed(v(1), 19) @ 9)
    (gapNext(v(1), 8) @ 9) (idNext(v(1), v(0)) @ 0) (histSpd(v(1), v(0), (20 @ 8) ; (20 @ 7) ; 20 @ 6) @ 8) maxAcc(v(1), 3) gapGreen(v(1), 1, 3)
    gapSafety(v(1), 2, 4)),
  ckb : none,
  sensors : (locS speedS gapS),
  evs : ((tick @ 1) (actSnd(v(1), msg(v(1), v(0), hbf2l(v(1), 19, loc(1172))) @ 9) @ 0) {u(1),actSpeed(v(1), 16, 16)} @ 0)]
[i(0) : infra |
  lkb : (clock(9) (atloc(v(0), loc(1160)) @ 8) (atloc(v(1), loc(1150)) @ 8) (atloc(v(2), loc(300)) @ 8) (i2vTrigger(i(0), v(2), 500, 50,
    nuPlatoon) @ 0) i2vTrigger(i(0), v(2), 600, 50, join(v(0))) @ 0),
  ckb : none,
  sensors : vehS,
  evs : (tick @ 0)]} ;
[iid : intruder |
  v2vMsgs : none
  blockActSnd : v(0)]}



search[1] asysint(60,1) =>* iasys such that bad-state(iasys) .
Solution 1 (state 628)
states: 629  rewrites: 748006 in 869ms cpu (870ms real) (860327 rewrites/second)
iasys --> {{
[eId |
  clock(3) class(v(0), veh) class(v(1), veh) class(v(2), veh) class(i(0), infra) (atloc(v(0), loc(1060)) @ 3) (atloc(v(1), loc(1014)) @ 3) (
    atloc(v(2), loc(175)) @ 3) (speed(v(0), 20) @ 3) (speed(v(1), 28) @ 3) (speed(v(2), 25) @ 0) (accel(v(0), 0) @ 3) (accel(v(1), 0) @ 3) accel(
    v(2), 0) @ 0]
[v(0) : veh |
  lkb : (clock(3) class(v(0), veh) (lastAct(actSpeed(v(0), 17, 23)) @ 2) (atloc(v(0), loc(1040)) @ 2) (atloc(v(1), loc(965)) @ 1) (mode(v(0),
    leading(v(1))) @ 0) (platoon(v(0), v(1)) @ 0) (speed(v(0), 20) @ 2) (speed(v(1), 23) @ 1) maxAcc(v(0), 3)),
  ckb : none,
  sensors : (locS speedS gapS),
  evs : ((tick @ 0) v2v(v(0), msg(v(1), v(0), hbf2l(v(1), 26, loc(988))) @ 2) @ 0)]
[v(1) : veh |
  lkb : (clock(3) class(v(1), veh) (lastAct(actSpeed(v(1), 25, 25)) @ 3) (atloc(v(0), loc(1040)) @ 2) (atloc(v(1), loc(1014)) @ 3) (mode(v(1),
    following(v(0))) @ 0) (platoon(v(0), v(1)) @ 0) (histGap(v(1), (46 @ 3) ; (52 @ 2) ; 55 @ 1) @ 3) (speed(v(0), 20) @ 2) (speed(v(1), 28) @ 3)
    (gapNext(v(1), 46) @ 3) (idNext(v(1), v(0)) @ 0) (histSpd(v(1), v(0), (20 @ 2) ; (60 @ 0) ; noVal) @ 2) maxAcc(v(1), 3) gapGreen(v(1), 1, 3)
    gapSafety(v(1), 2, 4)),
  ckb : none,
  sensors : (locS speedS gapS),
  evs : ((tick @ 1) (actSnd(v(1), msg(v(1), v(0), hbf2l(v(1), 28, loc(1014))) @ 3) @ 0) {u(1),actSpeed(v(1), 25, 25)} @ 0)]
[i(0) : infra |
  lkb : (clock(3) (atloc(v(0), loc(1040)) @ 2) (atloc(v(1), loc(988)) @ 2) (atloc(v(2), loc(150)) @ 2) (i2vTrigger(i(0), v(2), 500, 50,
    nuPlatoon) @ 0) i2vTrigger(i(0), v(2), 600, 50, join(v(0))) @ 0),
  ckb : none,
  sensors : vehS,
  evs : (tick @ 0)]} ;
[iid : intruder |
  v2vMsgs : none
  blockActSnd : v(0)]}

search[1] asysint(100,1) =>* iasys such that bad-state2(5,iasys) .
search [1] in TEST-INTRUDER : asysint(100, 1) =>* iasys such that bad-state2(5, iasys) = true .

Solution 1 (state 15941)
states: 15942  rewrites: 20659214 in 22581ms cpu (22610ms real) (914891 rewrites/second)
iasys --> {{
[eId |
  clock(7) class(v(0), veh) class(v(1), veh) class(v(2), veh) class(i(0), infra) (atloc(v(0), loc(1140)) @ 7) (atloc(v(1), loc(1143)) @ 7) (
    atloc(v(2), loc(275)) @ 7) (speed(v(0), 20) @ 7) (speed(v(1), 31) @ 7) (speed(v(2), 25) @ 0) (accel(v(0), 0) @ 7) (accel(v(1), 0) @ 7) accel(
    v(2), 0) @ 0]
[v(0) : veh |
  lkb : (clock(7) class(v(0), veh) (lastAct(actSpeed(v(0), 17, 23)) @ 7) (atloc(v(0), loc(1140)) @ 7) (atloc(v(1), loc(1109)) @ 6) (mode(v(0),
    leading(v(1))) @ 0) (platoon(v(0), v(1)) @ 0) (speed(v(0), 20) @ 7) (speed(v(1), 34) @ 6) (gapNext(v(0), 3) @ 7) maxAcc(v(0), 3)),
  ckb : none,
  sensors : (locS speedS gapS),
  evs : ((tick @ 1) (actSnd(v(0), msg(v(0), v(1), hbl2f(v(0), 20, loc(1140), (atloc(v(1), loc(1109)) @ 6) (platoon(v(0), v(1)) @ 0) speed(v(1),
    34) @ 6)) @ 7) @ 0) (actSnd(v(0), msg(v(0), v(1), hbl2j(v(0), v(1), 34, loc(1109))) @ 7) @ 0) {u(1),actSpeed(v(0), 17, 23)} @ 0)]
[v(1) : veh |
  lkb : (clock(7) class(v(1), veh) (lastAct(actSpeed(v(1), 31, 31)) @ 6) (atloc(v(0), loc(1100)) @ 5) (atloc(v(1), loc(1109)) @ 6) (mode(v(1),
    following(v(0))) @ 0) (platoon(v(0), v(1)) @ 0) (histGap(v(1), (11 @ 6) ; (25 @ 5) ; 37 @ 4) @ 6) (speed(v(0), 20) @ 5) (speed(v(1), 34) @ 6)
    (gapNext(v(1), 11) @ 6) (idNext(v(1), v(0)) @ 0) (histSpd(v(1), v(0), (20 @ 5) ; (100 @ 0) ; noVal) @ 5) maxAcc(v(1), 3) gapGreen(v(1), 1, 3)
    gapSafety(v(1), 2, 4)),
  ckb : none,
  sensors : (locS speedS gapS),
  evs : ((tick @ 0) (v2v(v(1), msg(v(0), v(1), hbl2f(v(0), 20, loc(1120), (atloc(v(1), loc(1075)) @ 5) (platoon(v(0), v(1)) @ 0) speed(v(1), 34)
    @ 5)) @ 6) @ 0) v2v(v(1), msg(v(0), v(1), hbl2j(v(0), v(1), 34, loc(1075))) @ 6) @ 0)]
[i(0) : infra |
  lkb : (clock(7) (atloc(v(0), loc(1120)) @ 6) (atloc(v(1), loc(1109)) @ 6) (atloc(v(2), loc(250)) @ 6) (i2vTrigger(i(0), v(2), 500, 50,
    nuPlatoon) @ 0) i2vTrigger(i(0), v(2), 600, 50, join(v(0))) @ 0),
  ckb : none,
  sensors : vehS,
  evs : (tick @ 0)]} ;
[iid : intruder |
  v2vMsgs : none
  blockActSnd : v(0)]}


 